### PR TITLE
Shield generator walls, wallening edition

### PR DESCRIPTION
**Pull request by SomeAngryMiner**
## About The Pull Request

Adds 3/4 shield generator walls, as per requested. 

image

All 8 directions are covered.

PR also includes _icons_ for smoothed edges for the shield extremes, if required. If not, it can be removed from the PR.

not included, but done, if needed, are new shield generators as well.

image

Repeated statement from last PR: Build.bat has decided to error itself to a better life on my local, so notify me of any modifications needed and i'll gladly do them.

## Why It's Good For The Game

maintaining perspective is good for the player eyes. Allegedly.

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
Noted. Will test locally and see if this helps with things at all (or gives us a route to improve at least)

**Comment by LemonInTheDark** [comment]
image
draftin for now

**Comment by SomeAngryMiner** [comment]
github please, i'm eating dinner, give me a second

**Comment by LemonInTheDark** [comment]
slave that you are to the machine

**Comment by SomeAngryMiner** [comment]
image

Draft for the required changes above alongside old one. Awaiting input, and if its good to go, i'll push it to the branch.

Smoothing would have to be adjusted to use external turf edges instead of a different state, but i assumed it was the cleanest way to do it without making a variant for each direction combination of shields deployed by the generator.

**Comment by LemonInTheDark** [comment]
looks fine to me, push it and I'll test it it works ok. keeping in mind that both the projector and the shield will be shifted up to fit with the style.
 (also what does external turf edges mean)

**Comment by SomeAngryMiner** [comment]
changes pushed, includind generator, better N/S shields, and the new edges.

Shield generator i split into an anchored and unanchored icon state, and the 'on' state has been turned into an overlay that can be applied as an emissive.

and by external turf edges i mean they draw on the adjacent tile, in this case the generator) instead of the native turf, i vaguely recall resin floors doing something similar.

image

Wow that image got really scrunchy

**Comment by LemonInTheDark** [comment]
sorry for the delay, looks good to me! Let me know if you're happy and I'll send this

**Pull request merged**
