### PR TITLE
Fixes APCs + Fixes Linters

### LINKED ISSUE #124: APCs are backwards during runtime
Runtime
image
In StrongDMM
image

### LINKED ISSUE #146: APCs' Terminals are backwards at mapload, Backwards themselves on construction
(This pictures were taken WITH #141. Without #141, APCS would be the inverse of these, directionally. Just clarifying.)

Mapload Terminals:
image

Player-Constructed APCs Have this as well, along with backwards APCs:
image

I've thrown myself at this, haven't cracked it yet, unfortunately. If anyone else wants to stab at it, be my guest.

### LINKED ISSUE #149: Wall Icons Are Failing test.py
```
Failed on: ./icons/turf/smoothrocks.dmi
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/runner/work/wallening/wallening/tools/dmi/test.py", line 39, in <module>
    _main()
  File "/home/runner/work/wallening/wallening/tools/dmi/test.py", line 33, in _main
    return _self_test()
  File "/home/runner/work/wallening/wallening/tools/dmi/test.py", line 16, in _self_test
    Dmi.from_file(fullpath)
  File "/home/runner/work/wallening/wallening/tools/dmi/__init__.py", line 63, in from_file
    assert next(line_iter) == f"version = {cls.version}"
AssertionError
Error: Process completed with exit code 1.
```
See https://github.com/wall-nerds/wallening/actions/runs/3349722403/jobs/5549980971, https://github.com/wall-nerds/wallening/actions/runs/3357349693/jobs/5563100078

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Removes the old broken APC Pixel Offset Code, making APCs finally appear correctly. This PR has been a massive clusterfuck but I'm cutting it off finally before it gets even more bloated.

Additionally, Fixes Linters. Yes, Really. Holy fuck.

Closes #124, Closes #149. Closes #146.

### CODE REVIEW

**Comment by unit0016** [comment]
```Failed on: ./icons/turf/smoothrocks.dmi
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/runner/work/wallening/wallening/tools/dmi/test.py", line 39, in <module>
    _main()
  File "/home/runner/work/wallening/wallening/tools/dmi/test.py", line 33, in _main
    return _self_test()
  File "/home/runner/work/wallening/wallening/tools/dmi/test.py", line 16, in _self_test
    Dmi.from_file(fullpath)
  File "/home/runner/work/wallening/wallening/tools/dmi/__init__.py", line 63, in from_file
    assert next(line_iter) == f"version = {cls.version}"
AssertionError
Error: Process completed with exit code 1.
```
Linters now progress enough to get this error message.

**Comment by unit0016** [comment]
Doing some additional tests on this one. I want to specifically see how terminals behave with APCs now (And document it in an issue report for how to handle it, since they're also used by SMES units) **AND** check on how building them works right now.

**Comment by unit0016** [comment]
> I want to specifically see how terminals behave with APCs now
image

Ack! Construction + terminals aren't.. handling this well. Going to fix this and check if mapload terminals are better.

**Comment by unit0016** [comment]
image
Mapload terminals are just straight up backwards oh god.

**Comment by unit0016** [comment]
I'm going to move these to an issue report - I've tried to look into dealing with both to put a cap on APCs, but unfortunately it seems I can't figure out how to get the terminals working. Pity.

**Comment by unit0016** [comment]
Fully acknowledging this PR's a bit of a clusterfuck, but I just want to confirm if it's an issue with how the DMI files are saved as I mentioned in #149. I'll revert the icon changes if I get a hit on one of the icons I've saved in run linters.

**Comment by unit0016** [comment]
If I get another hit I'm going thermonuclear and re-saving every wallening icon JUST to make sure.

**Comment by unit0016** [comment]
I wasn't expecting that to fix linters in totality, but I'm not complaining. Not one bit.

**Comment by unit0016** [comment]
Converting to draft as I'm going ALL the way and fixing all wallmounts with this now.

**Comment by unit0016** [comment]
Reverting that decision. I looked into trying it. Oh. Oh god. God no.

**Comment by unit0016** [comment]
do note wallmounts are.. kinda fucky, still. With this PR they're /less/ fucky, but they'll still be fucky.

**Comment by unit0016** [comment]
woman

**Comment by LemonInTheDark** [comment]
@unit0016 what was wrong with the linters exactly? If I recut the walls will they just start failing again

**Comment by unit0016** [comment]
> @unit0016 what was wrong with the linters exactly? If I recut the walls will they just start failing again

The cut icons were the problem, yeah - and yes. The solution is to go into byond and resave it ATM, which is dumb and should be addressed.
My guess? Something with the DMI metadata is engine-readable but not... correct?

**Comment by LemonInTheDark** [comment]
Ok, I will bully action about it then

**Comment by LemonInTheDark** [comment]
jhhhhhhhhhhhhhh

**Comment by unit0016** [comment]
I won't lie
that github-actions(Bot) do be spittin facts though

**Pull request merged**
