### PR TITLE
Moves mob shadows one pixel up

### PR DESCRIPTION
**Pull request by SmArtKar**
image

looks better now

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
It looks strange in context of the feet at least in the side by sides I've seen, I'm not sure I agree.
Do you have any comparisons to sell your point?

**Comment by SmArtKar** [comment]
image
image
the main reason for this change is sideways sprites specifically, currently they look like they're offset too much down - due to the size/shape of the shadow this leaves it offset slightly up, but that is less noticable

**Comment by LemonInTheDark** [comment]
I'd be ok with shifting the east/west sprites up and leaving the others I think that fits best. if you don't wanna do that that's fine we can handle this when the pr's merged

**Comment by LemonInTheDark** [comment]
Handling this postmerge

**Pull request closed without merging**
