### PR TITLE
Adds missing windows, updates smoothing logic somewhat, adds some new walls and wallsprites

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## About The Pull Request

[Adds in the missing window sprites in the new format](https://github.com/wall-nerds/wallening/commit/fd22f899fe47046cf231619c48e940705c5f8afe)

[Adds some new wall sprites, and support for non turf splitvis](https://github.com/wall-nerds/wallening/commit/5c216f689a8efbf6ff569a7b58b4d64c5f8bd87d)

bananium, plastium, and alien walls brother

[Gives hotel walls their proper icons](https://github.com/wall-nerds/wallening/commit/0db6255725ccdb8f0687414cf35633292ed6ff9f)

[adds a new 3/4ths sprite for the shitfuck wall](https://github.com/wall-nerds/wallening/commit/55ee45e21f4909167ab5c2fcda6d21650251b29f)

[uses the proper wall for hilberts](https://github.com/wall-nerds/wallening/commit/ba198d46963aa2270e2aafcd0b24f23e8cd351bb)

[ensures the old walls do not use splitvis](https://github.com/wall-nerds/wallening/commit/cb294dffb47f145ac401389dd237798932f0d8d3)

[changes shuttle smoothing a tad, ensures vis appearances are not offset by their home tile](https://github.com/wall-nerds/wallening/commit/6c8cd8c8a56f2952016461839fca1e25b6fdcf87)

[Adds a trait to splitvis, uses it to fix door below wall weirdness (doors can be opaque, this is dumb)](https://github.com/wall-nerds/wallening/commit/0a4375fc1f1edb698687f9949d998ddbfba3eea8)

## Why It's Good For The Game

Things are more pretty, windows actually work properly now, and we got all the windows in

### CODE REVIEW

**Comment by Twaticus** [comment]
will this be TMd cause thats a shitload of sprites 😳

**Comment by LemonInTheDark** [comment]
twat this is the wallening repo there's nothing to testmerge it onto
you're getting codeowner here because you're in the codeowners file and a member of the repo

**Comment by Twaticus** [comment]
sorry i thought we could TM into wallhall ignore me

**Comment by LemonInTheDark** [comment]
I mean we could if you wanted, you want me to?

**Comment by LemonInTheDark** [comment]
sending it

**Pull request merged**
