### PR TITLE
Offsets walls down instead of objects/mobs up

### PR DESCRIPTION
**Pull request by MrMelbert**
An alternate solution to the offset problem. 
Maybe won't be merged but we can at least test it. 

Pros:
- Much more maintainable.
   - Determine which objects need to be offset in line with walls, rather than determine which objects need to be offset away from walls. Way, way, way fewer objects need to be moved down rather than up.
   - Solves a bunch of hitbox / aim assist related issue (See: projectiles) naturally
   - Doesn't necessitate us shift all table objects on all maps up by a few pixels 
- Very similar, if not identical effect to what already exists 
- Keeps everything on the south side of the tile very visible without necessitating frill transparency
- People stay on the grid (they like that) 

Cons:
- Mild jank around darkness, primarily with diagonal angles 
- Loss of ~1/4th the north-most tile
   - Affects floor decals and floor-bound objects (vents, pipes, holopads). 
- May necessitate a few changes to rendering (primarily around emissives, windows, dirwindows from what I've seen, but nothing major or distracting) 

image

image

### CODE REVIEW

**Comment by LemonInTheDark** [comment]
For the record I am quite against this, but plan on giving it a test at some point to see how things look (owe melbert that much)

**Comment by dolphinemote** [comment]
temporary or weird solutions like this will get you nowhere. You either do a full perspective where everything including tiles is done in 3/4 or everything will be weird.

**Comment by MrMelbert** [comment]
I'd like to throw out there (in regards to #319) - if you search `new /obj/effect`, you get 743 results, and I would wager *over half* of them (mostly temp_visuals) are broken due to the offset and need to be manually fixed (Stuff like being dusted, being monkified, blood splatters, revenant animations, medbeams (beams in general))

This is what I mean by it being more maintainable, this is all stuff people in the future have to tackle

**Comment by JupiterJaeden** [comment]
So I heard about melbert doing this before and I was doubtful if it would really solve the core issues, but after playing a round with this, this is SO much better. Genuinely solves most of my major complaints about the wallening. Still a bit rough around the edges but the game actually feels playable still. Really good work melbert.

**Comment by junkgle01** [comment]
After playing a round with this-- I genuinely did not notice it until realizing I wasn't having trouble actually clicking on things on adjacent tiles... because I was on the grid, making it easier to actually know where I was relative to the item. Players DO like being on the grid. I know I do.

Regarding more maintainability above, shifting literally _every mob and related effect in the game_ instead of shifting the walls and adjusting the floor tiling to fit seems like much more of a trade off to me. This also solves the problem of having items be hidden under the lip of the wall overhang because they aren't shifted. And it still looks good!!

**Comment by Formerxboxgamer** [comment]
I had a chance to play this on Manuel last night. It was far far superior to current wallening with offsets. Everything felt better, more readable, and it didn’t sacrifice any visual fidelity with the walls. This should be seriously considered for merging and not just an experiment

**Comment by KingkumaArt** [comment]
Yeah I know this isnt what the wallening crew wants to hear, and I do genuinely like the look of the 3/4 walls in both this and the original incarnation, but this is just better to play. As people have noted before, the pixel shift REALLY screws with your muscle memory, more than you'd expect - or more than I expected, anyway. Also, as for the emissives and darkness jank - it's not like we dont have jank with those already.

**Comment by Nistishere** [comment]
This is a great version of the wallening ngl

**Comment by DrAmazing343** [comment]
Played a few rounds with this, seems to be making a huge difference in making things feel more "natural" so to speak. I truly think this is the sort of compromise that will make the game work better with the Wallening.

**Comment by Rex9001** [comment]
Having tested this now, I really like it, I think it looks good whilst keeping the original gamefeel better. The main issue are with wall tables, but thats a fairly easy fix

**Comment by Blacklist897** [comment]
this looks better

**Comment by MatrixOne500** [comment]
Looks better, smoother, more visibility on south tiles is welcome and I like my sprite being back on da grid

**Comment by Steel-Serperior** [comment]
Makes the wallening far more playable without too much compromise to the art style.

**Comment by LemonInTheDark** [comment]
Heyo. We're not doin this. Has visual problems that are dealbreakers and I consider the maintainability issues not having it causes to be bearable.
Unrelated, thank you melbert for poking at this, I respect you for it (I really wish we were able to have the discussion on this before the main pr, that's life tho)

**Comment by TheSmallBlue** [comment]
Could you say what the visual problems are? Seems like a somewhat vague reason to close a PR that has overwhelming approval

**Comment by LemonInTheDark** [comment]
We have discussed this extensively in maintainerbus, I am not interested in raking melbert over the coals over and over with details we disagree on. I am trying to justify this to HIM rather then you, which is why I have not been going into a deep amount of detail outside of that context.

**Comment by JupiterJaeden** [comment]
Well, this was the only shot for the wallening to actually be decent, at least that I've seen so far. This being closed puts me, and quite a few others evidently, firmly into the anti-wallening crowd.

**Comment by DrAmazing343** [comment]
Very disappointed to see this closed- I think that the outpouring of player support alone shows how much we needed to take this under more consideration. I know the attitude is by-and-large "don't let the door hit your ass on the way out," but I seriously do not think that the right approach is to give the finger to players grasping at straws for a compromise to continue playing TG.

**Pull request closed without merging**
