### PR TITLE
Loaded Defib Wallmount Helper & Wallenings The Starfury

### PR DESCRIPTION
**Pull request by unit0016**
## About The Pull Request
Acting on my claim in https://github.com/tgstation/tgstation/issues/85583

Screenshots of additional issues that cropped up in the process:

Transcribed Text: I assume this isn't Starfury specific and has more to do with midround map-template loading.
image

Transcribed text: Something is wrong with shuttleloading; the corvette broke in half and caused **this**. Not a basemap [the map being edited here] issue. I think.
image

### CODE REVIEW

**Comment by unit0016** [comment]
Drafting to deal with tables and look for any other big issues.

**Comment by unit0016** [comment]
Starfury's subshuttles still need work but those are separate tasks on the masterlist anyways. The starfury itself is as hot as I can make it.

**Comment by LemonInTheDark** [comment]
Code change goes hard, if I don't hear anythin bout the map from the tainers/tattle doesn't decend like an angel of death I'll merge like, tomorrow

**Comment by unit0016** [comment]
Just waiting on the offset consensus at this point for the maps between this and #299 ; yeah.

**Pull request merged**
